pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}
    stages {
        stage('Docker Login') {
            steps {
              sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
    }    
        stage('Build & push Dockerfile') {
            steps {
              sh """
              cd comingsoon/
              ansible-playbook playbook.yml
              """
            }
        }
        stage('Delete Cluster') {
            steps {
                  sh "kubectl delete cluster --name comingsoon-cluster"
                  sleep(time: 180, unit: "SECONDS")
                }
            }
        stage('Create Cluster') {
            steps {
                  sh """
                  kubectl create cluster --name comingsoon-cluster --region us-east-1 --nodes=2
                  aws eks update-kubeconfig --name comingsoon-cluster
                  """
                }
            }
        stage('Create Namespace') {
                  sh "kubectl create namespace comingsoon"
                }
        stage('Deploy') {
            steps {
                  sh """
                  cd comingsoon/k8s
                  kubectl -n comingsoon apply -f deployment.yaml
                  kubectl -n comingsoon apply -f services.yaml
                  """
                }
            }
    }
}
